version: '3'

services:
  api:
    build: .
    command: python -O app.py
    container_name: shiro-api
    ports:
      - "20377:8080"
    restart: unless-stopped


networks:
  default:
    driver: bridge
